# Generated by Django 6.0.3 on 2026-03-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to_entity',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='from_entity',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='schema',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('node_type', models.CharField(choices=[('process', 'Process (Square)'), ('decision', 'Decision (Diamond)'), ('start_end', 'Start/End (Rounded)')], default='process', max_length=20)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.schema')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.schema')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.node')),
            ],
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
